name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # TAMBAHKAN 3 BARIS DI BAWAH INI (Ganti 'nama-folder-project' sesuai folder tempat file gradlew Anda berada)
    defaults:
      run:
        working-directory: ./game-android 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle Executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # JANGAN LUPA sesuaikan path artifact ini juga jika berada di dalam folder
        path: game-android/app/build/outputs/apk/debug/app-debug.apk 
